steps:
    
    -   id: "Instalando o Go"
        name: "gcr.io/cloud-builders/go"
        args: ["install", "."]
        env: ['PROJECT_ROOT=src']
    
    -   id: "Rodando teste unitário"
        name: "gcr.io/cloud-builders/go"
        args: ["test"]
        env: ['PROJECT_ROOT=src']

images: ['gcr.io/$PROJECT_ID/desafio-ci']